version: "2"

run:
  timeout: 10m

formatters:
  enable:
    - gofmt
    - goimports

linters:
  default: standard
  enable:
    - bodyclose
    - errname
    - forbidigo
    - gocritic
    - gosec
    - importas
    - makezero
    - misspell
    - noctx
    - nolintlint
    - revive
    - unconvert
    - unparam
    - whitespace
